sonar.organization=victron-venus
sonar.projectKey=victron-venus_inverter-dashboard-go
sonar.sources=.
sonar.exclusions=**/*_test.go,**/vendor/**,**/*.pb.go
sonar.sourceEncoding=UTF-8
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.go.coverage.reportPaths=coverage.out
