#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")/.."
go mod download
golangci-lint run ./...
govulncheck ./...
go test -race -coverprofile=coverage.out -covermode=atomic ./...
python3 scripts/check-go-coverage.py 20
